language: node_js
node_js:
  - "stable"
cache: 
  directories:
  - "node_modules"
after_success: npm run coverage
services:
- postgresql
env:
- PGUSER=username PGPASSWORD=password PGDATABASE=db_name
before_script:
- psql -c 'create database db_name;' -U postgres
- psql -c "CREATE USER username WITH PASSWORD 'password';" -U postgres
